### ISSUE TITLE
Case Sensitivity 

### ISSUE THREAD

**Issue by rfc791** [Lucterios2/django_auth_ldap3_ad#1]
Not sure how to do a pull request.  I updated line 84 to be case insensitive.

```
uid = User.objects.filter(username__iexact=username).values_list('pk', flat=True)
usr = User.objects.get(pk=uid[0])
```

**Comment by povtux** [comment]
Hi,

I will soon deliver a new version taking this into account.

Thanks & best regards

**Comment by povtux** [comment]
Hi,
Should be good for now.
Regards
