### ISSUE TITLE
view example

### ISSUE THREAD

**Issue by jamil666** [Lucterios2/django_auth_ldap3_ad#15]
Hello. I already wrote all needed information to settings.py, but unfortunatly I do not understand what I should wright in views.py file. Can you help me and provide view file example?

**Comment by ghost** [comment]
I think this is not the right place for django questions.
Please find a django tutorial which guides you through the basics of a django app.

Like:
https://docs.djangoproject.com/en/1.11/intro/

When you have the app running without AD or LDAP connection, then you can activate this module and use LDAP for auth.

Cheers Seyhbold
