### ISSUE TITLE
Python 2 incompatibility: "str" in auth.py

### ISSUE THREAD

**Issue by jtv** [Lucterios2/django_auth_ldap3_ad#19]
In auth.py, update_user does:
```
                    if isinstance(attributes[settings.LDAP_ATTRIBUTES_MAP[attr]], str):
                        attribute_value = attributes[settings.LDAP_ATTRIBUTES_MAP[attr]]
                    else:
                        attribute_value = attributes[settings.LDAP_ATTRIBUTES_MAP[attr]][0]
```

This looks like it's meant to accept either a string or a list in attributes[settings.LDAP_ATTRIBUTES_MAP[attr]].

But the "str" in there is treacherous.  On python 2, that's the name of the "bytes" type, while the Unicode string type is called "unicode".

So, on python2, this code will see a string and think it's some kind of list.  And because a string is indexable, it reduces the username to just the first letter!

Some possible ways of fixing this:
- Is the code really supposed to accept a list or tuple in place of a username?  If not, maybe the easiest solution is simply to drop this check.
- Instead of isinstance(X, str) say isinstance(X, type(u'')).
- Depend on six and use six.text_type instead of str.

**Comment by povtux** [comment]
Hi,
Thanks for this comment. My first purpose developing this django module was that there was no LDAP/AD module working for Python3. So I develop and test only on Python3.

Issue #16 & #17 (witch are linked) are about the same problem. You propose to use six.text_type, he proposed to use six.string_type. As both are equivalent to str in PY3, this doesn't impact my tests. As you seam to know more than me on PY2 and be able to explain, between both choice, what is the best?

Actually, I merged the pull request with string_type but I am ready to change if it's not the best choice.

Thanks & regards

**Comment by jtv** [comment]
Actually I'm not that intimate with six, and I was typing off the top of my head, so I simply made a mistake.  :-)

Usually for me, type(u'') is _just_ enough to avoid adding a dependency, so that's what I normally do.  But once you're all packaged and on pypi, yes, what you've done looks like the right fix to me.

Thanks for getting this done so quickly!  I would recommend tox for running tests against python2 and python3.

**Comment by jtv** [comment]
Any chance of a new release?  We're patching this locally now every time we deploy, but we'd love to have the fix "out of the box."
