### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pedroteixeira** [Lucterios2/django_auth_ldap3_ad#20]
Hi,
Any chance to consider the license to be the same of django (BSD), or Apache or MIT?

Regards,
Pedro

**Comment by povtux** [comment]
Hi,
Actual license is GNU GPL V3, one of the most common opensource license. Do you have a reason to ask me for another one?

**Comment by pedroteixeira** [comment]
Hi, would you consider at least changing to LGPL? 
GPL v3 is a "viral license", and unfortunately would not be able to use this library with this license :/
best regards!
