### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mikedici** [Lucterios2/django_auth_ldap3_ad#26]
Is there an example configuration available?

**Comment by nova-systems** [comment]
All parameters you put inside your settings file.
you need to adjust CN,OU,DC to uor Active Directory / Ldap structure

my config:


#Active Directory
LDAP_SERVERS = [
    {
        'host': '10.172.90.3',
        'port': 389,
        'use_ssl': False,
    },
]
LDAP_ENGINE = "AD"
LDAP_BIND_USER = "cn=intranet,ou=EFEKTUM,dc=ad,dc=efektum,dc=pl"
LDAP_BIND_PASSWORD = ""
LDAP_SEARCH_BASE = "dc=ad,dc=efektum,dc=pl"
LDAP_USER_SEARCH_FILTER = "(&(|(userPrincipalName={0})(sAMAccountName={0}))(objectClass=user))"

DAP_USE_LDAP_GROUPS = True
LDAP_GROUPS_SEARCH_BASE = "dc=ad,dc=efektum,dc=pl"
LDAP_GROUPS_SEARCH_FILTER = "(&(objectClass=group))"
LDAP_GROUP_MEMBER_ATTRIBUTE = "member"
LDAP_SUPERUSER_GROUPS = ["CN=Administratorzy,DC=ad,DC=efektum,DC=pl", ]
LDAP_STAFF_GROUPS = ["CN=IT,OU=PROJEKTY,OU=EFEKTUM,DC=ad,DC=efektum,DC=pl", ]
LDAP_GROUPS_MAP = {
    'DPD': "CN=DPD,OU=PROJEKTY,OU=EFEKTUM,DC=ad,DC=efektum,DC=pl",
}
LDAP_ATTRIBUTES_MAP = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
}

**Comment by mikedici** [comment]
This was exactly what I needed.
