### ISSUE TITLE
IndexError in case LDAP attribute returns empty list

### ISSUE THREAD

**Issue by anpr** [Lucterios2/django_auth_ldap3_ad#31]
We use the newest version 1.6.33

We have an exception when logging in,
`IndexError: list index out of range`, in 

django_auth_ldap3_ad/auth.py in init_and_get_ldap_user at line 162
The value of `user_attribs[attrib]` is `[]`, i.e. the empty list. 

I think in that case, we'd need to set `None`. The code in question has been introduced with https://github.com/Lucterios2/django_auth_ldap3_ad/pull/30

**Comment by metalshanked** [comment]
same issue for me. have to revert to 1.6.30 since the newer ones have this error

**Comment by seancallaway** [comment]
+1 ing here.

Thanks, @metalshanked, for pointing to which version we need to revert to until this is fixed.

**Comment by metalshanked** [comment]
Thanks @seancallaway - Would a new version with this Fix be available on PyPi ?

**Comment by seancallaway** [comment]
@metalshanked, no one has merged in the PR or done the work to update the version number/deploy to PyPI.

Perhaps @povtux can review?

**Comment by anpr** [comment]
Thanks for the PR @seancallaway ! Would love to see this reviewed and merged.

**Comment by dominik-bln** [comment]
@povtux Any updates here? As the current version is broken for us a release with the proposed fix would be very appreciated.
